'''
print("I am statement -1")
print("I am statement -2")
print("I am statement -3")
print("I am statement -4")
print("I am statement -5")
print("I am statement -6")
print("I am statement -7")
print("I am statement -8")
print("I am statement -9")
print("I am statement -10")
print("I am statement -1")
print("I am statement -2")
print("I am statement -3")
print("I am statement -4")
print("I am statement -5")
print("I am statement -6")
print("I am statement -7")
print("I am statement -8")
print("I am statement -9")
print("I am statement -10")
'''

